# Basic
title: W.H.S.
subtitle: 学习笔记
welcome_message: <a href="https://wanghaoshuang.github.io" target="_blank"></a>
description: 学习
creator: <a href="https://wanghaoshuang.github.io">@wanghaoshuang</a>

url: "http://wanghaoshuang.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Github, description: My github, url: 'https://github.com/wanghaoshuang'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: wanghaoshuang
    # duoshuo: 
    
# Social
social:
    weibo: 王豪爽
    github: wanghaoshuang
    mail: jobwhs@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
